<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageValidationBaselineVersion>10.1.0</PackageValidationBaselineVersion>
    <TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
    <!-- TODO Remove once published to NuGet.org -->
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
  </PropertyGroup>

  <PropertyGroup>
    <Description>ASP.NET Core security middleware enabling Etsy authentication.</Description>
    <Authors>Sonja Schweitzer</Authors>
    <PackageTags>aspnetcore;authentication;etsy;oauth;security</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>

</Project>