<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageValidationBaselineVersion>9.1.0</PackageValidationBaselineVersion>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
  </PropertyGroup>
  
  <!-- TODO Remove once published to NuGet.org -->
  <PropertyGroup>
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
  </PropertyGroup>

  <PropertyGroup>
    <Description>ASP.NET Core security middleware enabling Atlassian authentication.</Description>
    <Authors>smnsht</Authors>
    <PackageTags>atlassian;aspnetcore;authentication;oauth;security</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>

</Project>
