<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageValidationBaselineVersion>9.4.0</PackageValidationBaselineVersion>
    <!-- TODO Remove once published to NuGet.org -->
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
    <TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>ASP.NET Core security middleware enabling Bilibili authentication.</Description>
    <Authors>Loongle Tse</Authors>
    <PackageTags>bilibili;aspnetcore;authentication;oauth;security</PackageTags>
  </PropertyGroup>
 
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>

</Project>
