<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageValidationBaselineVersion>9.1.0</PackageValidationBaselineVersion>
    <TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>

  <!-- TODO Remove once published to NuGet.org -->
  <PropertyGroup>
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
  </PropertyGroup>

  <PropertyGroup>
    <Description>ASP.NET Core security middleware enabling Douyin authentication.</Description>
    <Authors>Loongle Tse</Authors>
    <PackageTags>douyin;bytedance;aspnetcore;authentication;oauth;security</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>
</Project>