name: build

on:
  push:
    branches: [ dev, rel/* ]
    tags: [ '*' ]
  pull_request:
    branches: [ dev, rel/* ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - os: macos-latest
            os_name: macos
          - os: ubuntu-latest
            os_name: linux
          - os: windows-latest
            os_name: windows

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1

    - name: Build, Test and Package
      run: eng\common\CIBuild.cmd -configuration Release -prepareMachine
      if: ${{ runner.os == 'Windows' }}

    - name: Build, Test and Package
      shell: pwsh
      run: ./eng/common/cibuild.sh -configuration Release -prepareMachine
      if: ${{ runner.os != 'Windows' }}

    - name: Publish logs
      uses: actions/upload-artifact@v1
      with:
        name: logs-${{ matrix.os_name }}
        path: ./artifacts/log/Release

    - name: Publish NuGet packages
      uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.os_name }}
        path: ./artifacts/packages/Release/Shipping

    - name: Publish test results
      uses: actions/upload-artifact@v1
      with:
        name: testresults-${{ matrix.os_name }}
        path: ./artifacts/TestResults/Release

    - name: Push NuGet packages to aspnet-contrib MyGet
      run: dotnet nuget push "artifacts\packages\Release\Shipping\*.nupkg" --api-key ${{ secrets.MYGET_API_KEY }} --skip-duplicate --source https://www.myget.org/F/aspnet-contrib/ --symbol-source https://www.myget.org/F/aspnet-contrib/
      if: ${{ (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && runner.os == 'Windows' }}

    - name: Push NuGet packages to NuGet.org
      run: dotnet nuget push "artifacts\packages\Release\Shipping\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
      if: ${{ startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows' }}
