name: code-scan

on:
  push:
    branches: [ dev* ]
  pull_request:
    branches: [ dev* ]
  schedule:
    - cron: "0 12 * * MON"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "csharp" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10
      with:
        category: "/language:${{ matrix.language }}"
