name: code-scan

on:
  push:
    branches: [ dev* ]
  pull_request:
    branches: [ dev* ]
  schedule:
    - cron: '0 12 * * MON'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Initialize CodeQL
      uses: github/codeql-action/init@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
      with:
        build-mode: none
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
      with:
        category: '/language:${{ matrix.language }}'
