name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the SDK updates for.'
        required: false
        type: choice
        options:
          - 'dev'
          - 'dev-v9'
        default: 'dev'

permissions:
  contents: read
  pull-requests: read

jobs:
  update-sdk:
    name: Update .NET SDK
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@0bc908ef15be678a94bc7bf92f742bbaff67337e # v3.3.0
    permissions:
      contents: write
      pull-requests: write
    with:
      labels: 'dependencies,.NET'
      ref: ${{ inputs.branch || 'dev' }}
      update-nuget-packages: true
      user-email: ${{ vars.SERVICE_ACCOUNT_GIT_EMAIL }}
      user-name: ${{ vars.SERVICE_ACCOUNT_GIT_NAME }}
    secrets:
      application-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
      application-private-key: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
